package com.dev.javabwr;

public enum PTable {
    HYDROGEN(1, "Hydrogen"),
    HELIUM(2, "Helium"),
    LITHIUM(3, "Lithium"),
    BERYLLIUM(4, "Beryllium"),
    BORON(5, "Boron"),
    CARBON(6, "Carbon"),
    NITROGEN(7, "Nitrogen"),
    OXYGEN(8, "Oxygen"),
    FLUORINE(9, "Fluorine"),
    NEON(10, "Neon"),
    SODIUM(11, "Sodium"),
    MAGNESIUM(12, "Magnesium"),
    ALUMINUM(13, "Aluminum"),
    SILICON(14, "Silicon"),
    PHOSPHORUS(15, "Phosphorus"),
    SULFUR(16, "Sulfur"),
    CHLORINE(17, "Chlorine"),
    ARGON(18, "Argon"),
    POTASSIUM(19, "Potassium"),
    CALCIUM(20, "Calcium"),
    SCANDIUM(21, "Scandium"),
    TITANIUM(22, "Titanium"),
    VANADIUM(23, "Vanadium"),
    CHROMIUM(24, "Chromium"),
    MANGANESE(25, "Manganese"),
    IRON(26, "Iron"),
    COBALT(27, "Cobalt"),
    NICKEL(28, "Nickel"),
    COPPER(29, "Copper"),
    ZINC(30, "Zinc"),
    GALLIUM(31, "Gallium"),
    GERMANIUM(32, "Germanium"),
    ARSENIC(33, "Arsenic"),
    SELENIUM(34, "Selenium"),
    BROMINE(35, "Bromine"),
    KRYPTON(36, "Krypton"),
    RUBIDIUM(37, "Rubidium"),
    STRONTIUM(38, "Strontium"),
    YTTRIUM(39, "Yttrium"),
    ZIRCONIUM(40, "Zirconium"),
    NIOBIUM(41, "Niobium"),
    MOLYBDENUM(42, "Molybdenum"),
    TECHNETIUM(43, "Technetium"),
    RUTHENIUM(44, "Ruthenium"),
    RHODIUM(45, "Rhodium"),
    PALLADIUM(46, "Palladium"),
    SILVER(47, "Silver"),
    CADMIUM(48, "Cadmium"),
    INDIUM(49, "Indium"),
    TIN(50, "Tin"),
    ANTIMONY(51, "Antimony"),
    TELLURIUM(52, "Tellurium"),
    IODINE(53, "Iodine"),
    XENON(54, "Xenon"),
    CESIUM(55, "Cesium"),
    BARIUM(56, "Barium"),
    LANTHANUM(57, "Lanthanum"),
    CERIUM(58, "Cerium"),
    PRASEODYMIUM(59, "Praseodymium"),
    NEODYMIUM(60, "Neodymium"),
    PROMETHIUM(61, "Promethium"),
    SAMARIUM(62, "Samarium"),
    EUROPIUM(63, "Europium"),
    GADOLINIUM(64, "Gadolinium"),
    TERBIUM(65, "Terbium"),
    DYSPROSIUM(66, "Dysprosium"),
    HOLMIUM(67, "Holmium"),
    ERBIUM(68, "Erbium"),
    THULIUM(69, "Thulium"),
    YTTERBIUM(70, "Ytterbium"),
    LUTETIUM(71, "Lutetium"),
    HAFNIUM(72, "Hafnium"),
    TANTALUM(73, "Tantalum"),
    TUNGSTEN(74, "Tungsten"),
    RHENIUM(75, "Rhenium"),
    OSMIUM(76, "Osmium"),
    IRIDIUM(77, "Iridium"),
    PLATINUM(78, "Platinum"),
    GOLD(79, "Gold"),
    MERCURY(80, "Mercury"),
    THALLIUM(81, "Thallium"),
    LEAD(82, "Lead"),
    BISMUTH(83, "Bismuth"),
    POLONIUM(84, "Polonium"),
    ASTATINE(85, "Astatine"),
    RADON(86, "Radon"),
    FRANCIUM(87, "Francium"),
    RADIUM(88, "Radium"),
    ACTINIUM(89, "Actinium"),
    THORIUM(90, "Thorium"),
    PROTACTINIUM(91, "Protactinium"),
    URANIUM(92, "Uranium"),
    NEPTUNIUM(93, "Neptunium"),
    PLUTONIUM(94, "Plutonium"),
    AMERICIUM(95, "Americium"),
    CURIUM(96, "Curium"),
    BERKELIUM(97, "Berkelium"),
    CALIFORNIUM(98, "Californium"),
    EINSTEINIUM(99, "Einsteinium"),
    FERMIUM(100, "Fermium"),
    MENDELEVIUM(101, "Mendelevium"),
    NOBELIUM(102, "Nobelium"),
    LAWRENCIUM(103, "Lawrencium"),
    RUTHERFORDIUM(104, "Rutherfordium"),
    DUBNIUM(105, "Dubnium"),
    SEABORGIUM(106, "Seaborgium"),
    BOHRIUM(107, "Bohrium"),
    HASSIUM(108, "Hassium"),
    MEITNERIUM(109, "Meitnerium"),
    DARMSTADTIUM(110, "Darmstadtium"),
    ROENTGENIUM(111, "Roentgenium"),
    COPERNICIUM(112, "Copernicium"),
    NIHONIUM(113, "Nihonium"),
    FLEROVIUM(114, "Flerovium"),
    MOSCOVIUM(115, "Moscovium"),
    LIVERMORIUM(116, "Livermorium"),
    TENNESSINE(117, "Tennessine"),
    OGANESSON(118, "Oganesson");

    private final int atomicNumber;
    private final String name;

    PTable(int atomicNumber, String name) {
        this.atomicNumber = atomicNumber;
        this.name = name;
    }

    public int getAtomicNumber() {
        return atomicNumber;
    }

    public String getName() {
        return name;
    }
}